#!/usr/bin/env python3
"""
generate_ota_keys.py - Generate Ed25519 keypair for secure OTA firmware updates

This script generates a new Ed25519 keypair for signing ESP32Clock firmware updates.
The private key should be added as a GitHub Secret (OTA_SIGNING_KEY) and the public
key must be embedded in the firmware (ota_public_key.h).

Usage:
    python scripts/generate_ota_keys.py

Output:
    - Prints private key (hex) for GitHub Secrets
    - Updates include/ota_public_key.h with the public key
"""

import os
import sys

try:
    import nacl.signing
except ImportError:
    print("ERROR: PyNaCl library not installed.")
    print("Install with: pip install pynacl")
    sys.exit(1)


def generate_keypair():
    """Generate a new Ed25519 signing keypair."""
    signing_key = nacl.signing.SigningKey.generate()
    verify_key = signing_key.verify_key
    return signing_key, verify_key


def format_public_key_c_array(public_key_bytes):
    """Format public key bytes as C array initializer."""
    lines = []
    for i in range(0, 32, 8):
        chunk = public_key_bytes[i : i + 8]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_bytes}")
    return ",\n".join(lines)


def update_public_key_header(public_key_bytes, header_path):
    """Update the ota_public_key.h file with the new public key."""
    c_array = format_public_key_c_array(public_key_bytes)

    content = f'''#pragma once

/**
 * @file ota_public_key.h
 * @brief Ed25519 public key for OTA firmware signature verification.
 *
 * This key is used to verify that firmware updates are signed by the
 * authorized release process. The corresponding private key must be
 * kept secure and stored as a GitHub Secret (OTA_SIGNING_KEY).
 *
 * Generated by: scripts/generate_ota_keys.py
 *
 * IMPORTANT: If this key is changed, all previously signed firmware
 * will fail verification. Only update this key if the private key
 * has been compromised or you are deliberately rotating keys.
 */

// Ed25519 public key (32 bytes)
static const uint8_t OTA_PUBLIC_KEY[32] = {{
{c_array}
}};

// OTA signing is now configured
static const bool OTA_KEY_CONFIGURED = true;
'''

    with open(header_path, "w") as f:
        f.write(content)


def main():
    print("=" * 60)
    print("ESP32Clock OTA Key Generator")
    print("=" * 60)
    print()

    # Find project root (script should be in scripts/ directory)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    header_path = os.path.join(project_root, "include", "ota_public_key.h")

    if not os.path.exists(os.path.join(project_root, "platformio.ini")):
        print("ERROR: Could not find project root. Run from ESP32Clock directory.")
        sys.exit(1)

    print("Generating new Ed25519 keypair...")
    signing_key, verify_key = generate_keypair()

    private_key_hex = bytes(signing_key).hex()
    public_key_hex = bytes(verify_key).hex()
    public_key_bytes = bytes(verify_key)

    print()
    print("-" * 60)
    print("PRIVATE KEY (Keep this secret!)")
    print("-" * 60)
    print()
    print(f"  {private_key_hex}")
    print()
    print("Add this as a GitHub repository secret:")
    print("  1. Go to your repository Settings > Secrets and variables > Actions")
    print("  2. Click 'New repository secret'")
    print("  3. Name: OTA_SIGNING_KEY")
    print("  4. Value: (paste the hex string above)")
    print()
    print("-" * 60)
    print("PUBLIC KEY")
    print("-" * 60)
    print()
    print(f"  {public_key_hex}")
    print()

    # Update header file
    print(f"Updating {header_path}...")
    update_public_key_header(public_key_bytes, header_path)
    print("Done!")
    print()
    print("=" * 60)
    print("NEXT STEPS:")
    print("=" * 60)
    print("1. Add OTA_SIGNING_KEY secret to GitHub (see above)")
    print("2. Commit the updated include/ota_public_key.h")
    print("3. Create a new release to test signed updates")
    print()
    print("WARNING: Store the private key securely! If lost, you will")
    print("need to generate a new keypair and update all devices.")
    print()


if __name__ == "__main__":
    main()
