#pragma once

/**
 * @file ota_public_key.h
 * @brief Ed25519 public key for OTA firmware signature verification.
 *
 * This key is used to verify that firmware updates are signed by the
 * authorized release process. The corresponding private key must be
 * kept secure and stored as a GitHub Secret (OTA_SIGNING_KEY).
 *
 * Generated by: scripts/generate_ota_keys.py
 *
 * IMPORTANT: If this key is changed, all previously signed firmware
 * will fail verification. Only update this key if the private key
 * has been compromised or you are deliberately rotating keys.
 */

// Ed25519 public key (32 bytes)
static const uint8_t OTA_PUBLIC_KEY[32] = {
    0xbb, 0xca, 0xc8, 0x9f, 0xfd, 0x0b, 0xbf, 0xd6,
    0x04, 0x54, 0xd0, 0xe7, 0xf2, 0x5a, 0x59, 0xb8,
    0xe3, 0x42, 0xe2, 0x19, 0x28, 0x31, 0x0d, 0x0c,
    0xb1, 0xa6, 0x1b, 0x24, 0xc1, 0x31, 0x11, 0x6b
};

// OTA signing is now configured
static const bool OTA_KEY_CONFIGURED = true;
